# Generated by Django 5.1.5 on 2025-02-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_student_name_remove_teacher_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
